=== CalvinKirs/incubator/output/podlings.dtd
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<!--  DTD for podlings.xml -->
<!ELEMENT podlings (podling+)>

<!ELEMENT podling (description, reporting?, graduating?, retiring?, resolution?, champion?, mentors)>
<!ATTLIST podling name CDATA #REQUIRED>
<!ATTLIST podling longname CDATA #IMPLIED>
<!ATTLIST podling status (current|graduated|retired) #REQUIRED>
<!ATTLIST podling resource CDATA #REQUIRED>
<!-- comma-separated list of alternate resource names -->
<!ATTLIST podling resourceAliases CDATA #IMPLIED>
<!ATTLIST podling sponsor CDATA #REQUIRED>
<!-- Format yyyy-mm-dd -->
<!ATTLIST podling startdate CDATA #REQUIRED>
<!-- Format yyyy-mm-dd -->
<!ATTLIST podling enddate CDATA #IMPLIED>

<!-- 
    Specifies the reporting group for podlings with status="current"
    The text field is used to specify the monthly report details (e.g. June, July, Agust)
-->
<!ELEMENT reporting  (#PCDATA)  >
<!--
    1 = January, April, July, October
    2 = February, May, August, November
    3 = March, June, September, December
-->
<!ATTLIST reporting group (1|2|3) #REQUIRED>
<!-- optional attribute for monthly reports -->
<!ATTLIST reporting monthly (true|false) #IMPLIED>

<!-- optional empty elements to flag podlings that are graduating or retiring -->
<!ELEMENT graduating EMPTY >
<!ELEMENT retiring EMPTY >
<!-- required list of mentors -->
<!ELEMENT mentors (mentor+)>
<!ELEMENT mentor  (#PCDATA)  >
<!ATTLIST mentor username CDATA #REQUIRED>
<!ELEMENT description  (#PCDATA)  >

<!-- The (optional) text is mainly used to comment on the reason for retirement -->
<!ELEMENT resolution  (#PCDATA)  >
<!ATTLIST resolution url CDATA #IMPLIED>
<!-- link defaults to the @name and is used for the link text -->
<!ATTLIST resolution link CDATA #IMPLIED>
<!-- tlp="true" means generate link from @name and @resource, rather than url and link -->
<!ATTLIST resolution tlp CDATA #IMPLIED>

<!ELEMENT champion  (#PCDATA)  >
<!ATTLIST champion availid CDATA #IMPLIED>

=== CalvinKirs/incubator/podlings.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="podlings.xsl" type="text/xsl" ?>

<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

<!--
    See the DTD for allowable elements and attributes.
    Note that description must precede mentors, and most of the podling attributes are required.
 -->
<!DOCTYPE podlings SYSTEM "podlings.dtd">

<podlings>
    <podling name="Abdera" status="graduated" resource="abdera" sponsor="Incubator" startdate="2006-06-06" enddate="2008-11-08">
        <description>An implementation of the Atom Syndication Format and Atom Publishing Protocol.</description>
        <resolution tlp="true"/>
        <mentors>
            <mentor username="rooneg">Garrett Rooney</mentor>
            <mentor username="querna">Paul Querna</mentor>
        </mentors>
    </podling>
    <podling name="Accumulo" status="graduated" resource="accumulo" sponsor="Incubator" startdate="2011-09-12" enddate="2012-03-21">
        <description>Accumulo is a distributed key/value store that provides expressive, cell-level access labels.</description>
        <resolution tlp="true"/>
        <mentors>
            <mentor username="bimargulies">Benson Margulies</mentor>
            <mentor username="adc">Alan Cabrera</mentor>
            <mentor username="berndf">Bernd Fondermann</mentor>
        </mentors>
    </podling>
    <podling name="ACE" status="graduated" resource="ace" sponsor="Board" startdate="2009-04-24" enddate="2011-12-21">
        <description>A software distribution framework based on OSGi that allows you to manage and distribute artifacts.</description>
        <resolution tlp="true"/>
        <mentors>
            <mentor username="niclas">Niclas Hedhman</mentor>
            <mentor username="cziegeler">Carsten Ziegeler</mentor>
            <mentor username="bdelacretaz">Bertrand Delacr√©taz</mentor>
        </mentors>
    </podling>
    <podling name="ActiveMQ" status="graduated" resource="activemq" sponsor="Geronimo" startdate="2005-12-01" enddate="2007-02-06">
        <description>A robust and high performance Message Orientated Middleware provider which will be integrated into Apache Geronimo but also be usable from inside any JVM.</description>
        <resolution tlp="true"/>
        <mentors>
            <mentor username="jstrachan">James Strachan</mentor>
        </mentors>
    </podling>
    <podling name="Agila" status="retired" resource="agila" sponsor="Jakarta" startdate="2004-09-29" enddate="2006-12-05">
        <description>Extensible Business Process Management (BPM) engine core.</description>
        <resolution link="ODE" url="ode.html">Project activity transferred to another Incubator project - ODE.</resolution>
        <mentors>
            <mentor username="geirm">Geir Magnusson Jr.</mentor>
        </mentors>
    </podling>
    <podling name="Airavata" status="graduated" resource="airavata" sponsor="Board" startdate="2011-05-05" enddate="2012-09-19">
        <description>A software suite to compose, manage, execute, and monitor large scale applications and workflows on computational resources ranging from local clusters to national grids and computing clouds.</description>
        <resolution tlp="true"/>
        <champion availid="rgardler">Ross Gardler</champion>
        <mentors>
            <mentor username="aslom">Alek Slominski</mentor>
            <mentor username="ate">Ate Douma</mentor>
            <mentor username="sanjiva">Sanjiva Weerawarana</mentor>
            <mentor username="mattmann">Chris Mattmann</mentor>
        </mentors>
    </podling>
    <podling name="Airflow" status="current" resource="airflow" sponsor="Incubator" startdate="2016-03-31">
        <description>Airflow is a workflow automation and scheduling system that can be used to author and manage data pipelines.</description>
        <reporting group="1"/>
        <champion availid="criccomini">Chris Riccomini</champion>
        <mentors>
            <mentor username="cnauroth">Chris Nauroth</mentor>
            <mentor username="hitesh">Hitesh Shah</mentor>
            <mentor username="jghoman">Jakob Homan</mentor>
        </mentors>
    </podling>
    <podling name="Allura" status="graduated" resource="allura" sponsor="Incubator" startdate="2012-06-25" enddate="2014-03-19">
        <description>Forge software for the development of software projects, including source control systems, issue tracking, discussion, wiki, and other software project management tools.</description>
        <resolution tlp="true"/>
        <champion availid="rbowen">Rich Bowen</champion>
        <mentors>
            <mentor username="rgardler">Ross Gardler</mentor>
            <mentor username="gstein">Greg Stein</mentor>
            <mentor username="jim">Jim Jagielski</mentor>
        </mentors>
    </podling>
    <podling name="Alois" status="retired" resource="alois" sponsor="Incubator" startdate="2010-09-21" enddate="2011-06-30">
        <description>ALOIS is a log collection and correlation software with reporting and alarming functionalities.</description>
      <resolution>Podling requested to be retired</resolution>
        <mentors>
            <mentor username="sdeboy">Scott Deboy</mentor>
            <mentor username="grobmeier">Christian Grobmeier</mentor>
        </mentors>
    </podling>
    <podling name="AltRMI" status="retired" resource="altrmi" sponsor="Incubator" startdate="2003-02-13" enddate="2007-01-18">
        <description>A transparent Remote Procedure Call bean.</description>
        <resolution link="JRemoting" url="http://jremoting.codehaus.org/">Development stalled and the project activity transferred to JRemoting</resolution>
        <mentors>
            <mentor username="hammant">Paul Hammant</mentor>
        </mentors>
    </podling>
    <podling name="Ambari" status="graduated" resource="ambari" sponsor="Incubator" startdate="2011-08-30" enddate="2013-11-20">
        <description>Ambari is a monitoring, administration and lifecycle management project for Apache Hadoop clusters.</description>
        <resolution tlp="true"/>
        <mentors>
            <mentor username="omalley">Owen O'Malley</mentor>
            <mentor username="cdouglas">Chris Douglas</mentor>
            <mentor username="acmurthy">Arun Murthy</mentor>
        </mentors>
    </podling>
    <podling name="Amber" status="graduated" resource="amber" resourceAliases="oltu" sponsor="Shindig" startdate="2010-05-09" enddate="2013-01-16">
        <description>The Amber project will deliver a Java development framework mainly aimed to build OAuth-aware applications.
        Amber graduated with the name Apache Oltu
        </description>
        <resolution url="http://oltu.apache.org"/>
        <mentors>
            <mentor username="jfclere">Jean-Frederic Clere</mentor>
            <mentor username="gianugo">Gianugo Rabellino</mentor>
            <mentor username="djencks">David Jencks</mentor>
            <mentor username="rfeng">Raymond Feng</mentor>
        </mentors>
    </podling>
    <podling name="Annotator" status="current" resource="annotator" sponsor="Incubator" startdate="2016-08-30">
        <description>Annotator provides annotation enabling code for browsers, servers, and humans. </description>
      <reporting group="1" monthly="true">October, November, December, January</reporting> 
      <champion availid="humbedooh">Daniel Gruno</champion>
        <mentors>
          <mentor username="niq">Nick Kew</mentor>
          <mentor username="brianm">Brian McCallister</mentor>
          <mentor username="humbedooh">Daniel Gruno</mentor>
          <mentor username="jim">Jim Jagielski</mentor>
        </mentors>
    </podling>
    <podling name="Any23" status="graduated" resource="any23" sponsor="Tika" startdate="2011-10-01" enddate="2012-08-28">
        <description>Anything To Triples (any23) is a library, a web service and a command line tool that extracts structured data in RDF format from a variety of Web documents.</description>
        <resolution tlp="true"/>
        <mentors>
            <mentor username="mattmann">Chris Mattmann</mentor>
            <mentor username="niq">Nick Kew</mentor>
            <mentor username="pramirez">Paul Ramirez</mentor>
            <mentor username="simonetripodi">Simone Tripodi</mentor>
            <mentor username="tommaso">Tommaso Teofili</mentor>
        </mentors>
    </podling>
    <podling name="Apex" status="graduated" resource="apex" sponsor="Incubator" startdate="2015-08-17" enddate="2016-04-20">
        <description>Apex is an enterprise grade native YARN big data-in-motion platform that unifies stream processing as well as batch processing.</description>
        <resolution tlp="true"/>
        <champion availid="tdunning">Ted Dunning</champion>
        <mentors>
            <mentor username="cnauroth">Chris Nauroth</mentor>
            <mentor username="gates">Alan Gates</mentor>
            <mentor username="hitesh">Hitesh Shah</mentor>
            <mentor username="jmclean">Justin Mclean</mentor>
            <mentor username="ptgoetz">P. Taylor Goetz</mentor>
            <mentor username="tdunning">Ted Dunning</mentor>
        </mentors>
    </podling>
